module.exports = {
  PORT: process.env.PORT || 3000,
  JWT_SECRET: process.env.JWT_SECRET || "REPLACE_WITH_STRONG_JWT_SECRET",
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN || "TELEGRAM_BOT_TOKEN",
  TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID || "TELEGRAM_CHAT_ID",

  // SMS Eskiz
  ESKIZ_EMAIL: "dilobar.zhuraeva.97@gmail.com",
  ESKIZ_PASSWORD: "ESKIZ_PASSWORD",
  ESKIZ_FROM: "SALON"
};
